Carrrusel/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CarruselApp.urls')),
]

CarruselApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('/carrusel/', views.carrusel_main, name='carrusel_main'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CarruselApp/models.py
from django.db import models


# Create your models here.

class OrdenTrabajo(models.Model):
    numero_orden = models.CharField('Número orden', primary_key=True, max_length=30)
    estado = models.IntegerField(default=1)

    class Meta:
        verbose_name = "OrdenDeTrabajo"
        verbose_name_plural = "OrdenDeTrabajos"

    def __str__(self):
        return '{}'.format(self.numero_orden)


class ImageOrdenTrabajo(models.Model):
    orden = models.ForeignKey(OrdenTrabajo, on_delete=models.PROTECT)
    fecha_public = models.DateTimeField(auto_now_add=True, null=True)
    image = models.ImageField(null=True, blank=True, upload_to="image/%Y/%m/%d")

    class Meta:
        verbose_name = "ImagenOrdenDeTrabajo"
        verbose_name_plural = "ImagenOrdenDeTrabajos"

CarruselApp/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponse
from .models import *


# Create your views here.

def home(request):
    context = RequestContext(request)
    order = OrdenTrabajo.objects.filter(estado=1)
    img_order = []
    context['order'] = order
    context['img_order'] = img_order
    return render(request, 'Home.html', context.flatten())


def carrusel_main(request):
    context = RequestContext(request)
    try:
        _order = request.POST['orden']
        if _order == '':
            img_order = []
            context['img_order'] = img_order
            return render(request, 'carrusel_main.html', context.flatten())

        img_order = ImageOrdenTrabajo.objects.filter(orden=_order)
        context['img_order'] = img_order
    except Exception as e:
        print('{} - Función: {}'.format(e, 'carrusel_main'))
        return HttpResponse(status=500)

    return render(request, 'carrusel_main.html', context.flatten())

CarruselApp/templates/Home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ResponsiveSlides.js &middot; Alternative themes</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="{% static '/bootstrap/dist/css/responsiveslides.css' %}">
  <link rel="stylesheet" href="{% static '/bootstrap/dist/css/themes.css' %}">
  <script src="{% static '/bootstrap/dist/js/jquery.min.js' %}"></script>
  <script src="{% static '/bootstrap/dist/js/responsiveslides.min.js' %}"></script>


    <script>

    function buscar() {
        let orden = $('#id_orden').val();
        $.ajax({
            url: "{% url 'carrusel_main' %}",
            type: 'post',
            headers: {'X-CSRFToken': '{{ csrf_token }}'},
            datatype: 'json',
            data: {orden: orden},
            statusCode: {
                200: function (data) {
                    $("#carrusel").html(data);
                },
                500: function () {

                    toastr.error(gettext('Server error, contact an administrator.'), ' ', {timeOut: 2000})
                }
            }
        });
    }
</script>
</head>
<body>
    <div >
        <div class="form">
            <div class="form-group">
                <h2>Ordenes de trabajo:</h2>
                <br>
                <select class="form-control" type="text" id="id_orden" name="OrdenTrabajo" onchange="buscar()">
                    <option value="">Seleccionar...</option>
                    {% for o in order %}
                        <option value="{{ o.numero_orden }}">{{ o.numero_orden }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
<hr>
<br>
    <div id='carrusel' >
        {% include 'carrusel_main.html' with feedback_form=feedback_form %}
    </div>

</body>
</html>

CarruselApp/templates/carrusel_main.html
{% load static %}

  <div id="wrapper">
    <h3>Imágenes de la orden</h3>
    <!-- Slideshow 3 -->
    <div class="rslides_container">
      <ul class="rslides" id="slider3">
          {% for img in img_order %}
            <li><img src="{{ img.image.url }}" alt=""></li>
          {% endfor %}
      </ul>
    </div>

  </div>

<script>
    // You can also use "$(window).load(function() {"
    $(function () {
      $("#slider3").responsiveSlides({
        auto: false,
        pager: false,
        nav: true,
        speed: 500,
        maxwidth: 800,
        namespace: "large-btns"
      });

    });
  </script>